<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DZO</name>
   <tag></tag>
   <elementGuidId>cfff11c9-1ec2-4508-905a-72fe5ecd7fb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='widget-header-46034309518648d3aae2a0edf828f0fe']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#widget-header-e7b741b5bd964408a0aa5ad1f85a1fe3 > a.va-widget-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>67898f10-6e35-47f7-adf8-479683f47025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>va-widget-header</value>
      <webElementGuid>52cbd055-814f-46bf-9e47-140ee6f8ac13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: title.text(), attr: title.linkEnabled() &amp;&amp; title.link().trim() ? { href: title.link().indexOf('http') == 0 ? title.link().trim() : '//' + title.link().trim() } : { href: false }, style: { 'text-align': title.textStyle.alignString(), color: title.textStyle.color(), 'font-size': title.textStyle.fontSize() + 'px', 'font-family': title.textStyle.fontFamily(), 'font-weight': title.textStyle.isBold() ? 'bold' : 'normal', 'font-style': title.textStyle.isItalic() ? 'italic' : 'normal', 'line-height': title.textStyle.lineHeight(), cursor: title.linkEnabled() ? 'pointer' : 'default' }</value>
      <webElementGuid>2b92daa5-78c9-4d36-8347-83034adccb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ДЗО</value>
      <webElementGuid>eaddcd9a-dbdd-4ce8-b05b-e572482416e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget-header-e7b741b5bd964408a0aa5ad1f85a1fe3&quot;)/a[@class=&quot;va-widget-header&quot;]</value>
      <webElementGuid>03a2bc67-18f5-40bf-9426-5ac2009aa7aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-header-e7b741b5bd964408a0aa5ad1f85a1fe3']/a</value>
      <webElementGuid>2c993575-84c7-4cb9-ba0c-3b35b1e1c767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ДЗО')]</value>
      <webElementGuid>186fa028-6f04-43c4-8669-6b717b41075f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[5]/following::a[1]</value>
      <webElementGuid>ed69fbb0-c75a-477c-9311-a36a22db60c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='_________________________________________'])[1]/following::a[1]</value>
      <webElementGuid>b07330e1-a1e8-4480-ab95-940ea62ed268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Все'])[1]/preceding::a[1]</value>
      <webElementGuid>3aaa435d-f201-4958-aec8-ddaaa3ab5abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выбранные значения'])[1]/preceding::a[1]</value>
      <webElementGuid>41f0c669-89b0-48be-8328-19dfd8617499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ДЗО']/parent::*</value>
      <webElementGuid>77497ad8-336a-40d7-96ba-0bf2cf776883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/a</value>
      <webElementGuid>fecbc0cc-2d44-4163-8b4b-837bb238ecb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'ДЗО' or . = 'ДЗО')]</value>
      <webElementGuid>4a134e20-4c27-43b1-8131-3dce493c48df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
