<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentEducationHigher</name>
   <tag></tag>
   <elementGuidId>711d7022-68bd-43a4-b400-4e401c597cc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[50]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#468ab12773094e5091f46fad9889ea76 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4a67476-60b9-4272-abbb-f21e6fcafbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>96.4%</value>
      <webElementGuid>005a2850-8dee-48a2-a577-e257e6fb104b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;468ab12773094e5091f46fad9889ea76&quot;)/div[1]</value>
      <webElementGuid>ab505ff9-d306-48ab-add5-6706a17c7d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='468ab12773094e5091f46fad9889ea76']/div</value>
      <webElementGuid>f03eabb0-0511-4cd4-b74e-d2c57536303b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Образование (в % и чел.) - копия 1'])[2]/following::div[3]</value>
      <webElementGuid>c107e15a-b768-44c1-bb3a-f35e8eb889c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[25]/following::div[9]</value>
      <webElementGuid>c376935c-bc38-4b69-be3a-53df640eb859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[26]/preceding::div[16]</value>
      <webElementGuid>607a5d1d-77d7-4a56-a6c6-c9a250e7ba74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='96.4%']/parent::*</value>
      <webElementGuid>172d25cf-1113-4537-ae40-e7636e021d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[50]/div[2]/div/div</value>
      <webElementGuid>7f4f78a8-8290-4db8-b0d6-8fc83f0ebcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '96.4%' or . = '96.4%')]</value>
      <webElementGuid>cfd0fec4-7f5c-4650-8722-f1448c306e42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
