<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperienceMoreThan40</name>
   <tag></tag>
   <elementGuidId>5663ef09-3452-4835-a8b8-98e012fa6bf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[64]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e3d635b1af904eebaca64a28d311db1c > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>62443eaa-91ea-4f89-8212-961533d46630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.0%</value>
      <webElementGuid>9089108d-0e66-4ec3-92d6-6b3490e0fbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e3d635b1af904eebaca64a28d311db1c&quot;)/div[1]</value>
      <webElementGuid>84137b76-ca58-4da9-b197-e059ca3abaac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e3d635b1af904eebaca64a28d311db1c']/div</value>
      <webElementGuid>33fb6e74-bd69-4909-ae1c-2bbbd5225676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[32]/following::div[9]</value>
      <webElementGuid>32452611-ea5f-4d4c-8d05-539e9670df02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[33]/preceding::div[16]</value>
      <webElementGuid>e6ea85e2-fce3-4d9d-ac8c-a3d3c1469be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Возраст (в % и чел.) - копия'])[1]/preceding::div[24]</value>
      <webElementGuid>d568c357-10db-4cdd-a8df-d57b1a9aceb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[64]/div[2]/div/div</value>
      <webElementGuid>90a47847-3e46-4a30-9e6c-7495ae77947a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0.0%' or . = '0.0%')]</value>
      <webElementGuid>8d57d516-2b19-41cf-a6aa-d8e03028abbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
