<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentAgeBelow50</name>
   <tag></tag>
   <elementGuidId>029707fd-471c-4e0a-b379-ddd9fa12de66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[70]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#87b557eb680846eb8f1852a2f171a646 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>047fc165-cb6d-4d01-a601-441bceda73f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30.9%</value>
      <webElementGuid>ffc60e47-2f00-46ed-9316-80b56f04afac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;87b557eb680846eb8f1852a2f171a646&quot;)/div[1]</value>
      <webElementGuid>36b0c33b-b027-4ea1-b32a-91d5c4fe7b49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='87b557eb680846eb8f1852a2f171a646']/div</value>
      <webElementGuid>3b06310d-c76d-421b-bcfb-8f466a90ca9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Возраст (в % и чел.) - копия 1'])[2]/following::div[3]</value>
      <webElementGuid>86049783-167d-4b91-a8ca-031100707de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[35]/following::div[9]</value>
      <webElementGuid>2294994b-db61-44b5-b1d0-6ce84312c67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Экспорт данных'])[1]/preceding::div[17]</value>
      <webElementGuid>2f4984fd-eee3-47df-b2d2-2c6640959d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отменить загрузку'])[1]/preceding::div[18]</value>
      <webElementGuid>dd339a42-025f-42d6-b529-c3da6e7e5c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30.9%']/parent::*</value>
      <webElementGuid>6cf4c3d0-b844-45c8-94a8-96642fd2fc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[70]/div[2]/div/div</value>
      <webElementGuid>399b382f-c0d2-4ac9-ad8b-0dccfe2ce63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '30.9%' or . = '30.9%')]</value>
      <webElementGuid>a2b4f191-e22b-4e3f-bda5-ae7506aa055f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
