<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentOfMen</name>
   <tag></tag>
   <elementGuidId>7b3637b6-719c-42fe-9c3e-7e6b6746a32f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[14]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a551f2e38a714e31a46bf4a9b701a490 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3cc47250-3b75-45e9-8b7e-ff85a1769ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>1245b1c8-9082-4093-b5bb-7a0f50595fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a551f2e38a714e31a46bf4a9b701a490&quot;)/div[1]</value>
      <webElementGuid>41117d91-aed6-4b19-8b85-aa355d8f73f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a551f2e38a714e31a46bf4a9b701a490']/div</value>
      <webElementGuid>a670e2a6-09fc-459a-9368-4546487539a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Мужчин, %'])[1]/following::div[3]</value>
      <webElementGuid>a36349cb-e383-4fef-a056-72089e35bf0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[7]/following::div[9]</value>
      <webElementGuid>18ab13ce-a42f-4830-8ca3-eafad03d880a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[8]/preceding::div[16]</value>
      <webElementGuid>062dd7de-9aa9-469f-8a16-d2b2f0906d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Женщин, %'])[1]/preceding::div[24]</value>
      <webElementGuid>2289134c-50b4-40b8-859d-aedd02c76db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='50%']/parent::*</value>
      <webElementGuid>3415e8a8-f643-4fa9-90c0-387a72180e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/div/div</value>
      <webElementGuid>c4d95ae8-2d83-4854-b031-7108a9a14adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '50%' or . = '50%')]</value>
      <webElementGuid>4dad9101-f1a0-4eb2-8e58-331e6328b854</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
