<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience1</name>
   <tag></tag>
   <elementGuidId>8d74e2d5-c4f7-4ef4-99d0-94d33f2cd494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[52]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9e572aa41f764616a5a15f3af5146008 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95c8ef9b-da02-4733-8d0c-099c8a5c09ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7.1%</value>
      <webElementGuid>beed4618-baae-4191-83cf-9468a34907f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9e572aa41f764616a5a15f3af5146008&quot;)/div[1]</value>
      <webElementGuid>fc4c813a-9523-4a1e-a76a-797b5f3cf265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9e572aa41f764616a5a15f3af5146008']/div</value>
      <webElementGuid>3e0e1488-6c80-4f31-934a-3da4d0e3a2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[26]/following::div[9]</value>
      <webElementGuid>fda6febf-7377-450d-9a8e-c300d36b7a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[27]/preceding::div[16]</value>
      <webElementGuid>8b11be58-58d2-496d-a12e-0d178f3ff239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7.1%']/parent::*</value>
      <webElementGuid>2edbf37a-4ec3-49a3-b75b-c6a69cd8def5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[52]/div[2]/div/div</value>
      <webElementGuid>68dc47d9-dd0a-4730-9ce6-18fc6b7e6cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '7.1%' or . = '7.1%')]</value>
      <webElementGuid>48e476b4-2982-4358-bb00-8559b7080bb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
