<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience10</name>
   <tag></tag>
   <elementGuidId>910978f5-54fa-46dd-8eff-b1195b537cd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[56]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eba1a8b66362466b815e0de28477c634 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dda78eeb-ed57-4e08-851d-548f7bc95d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>33.3%</value>
      <webElementGuid>492b4f7d-378b-4929-8ea9-be315683b5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eba1a8b66362466b815e0de28477c634&quot;)/div[1]</value>
      <webElementGuid>a268b787-71a1-4ecf-aed2-ce56e3dd7b40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eba1a8b66362466b815e0de28477c634']/div</value>
      <webElementGuid>fe091994-3476-4412-9bf4-be78dfb8f12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[28]/following::div[9]</value>
      <webElementGuid>5a263d9e-1b20-4ed9-819b-2880b4bbb645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[29]/preceding::div[16]</value>
      <webElementGuid>f2f68a04-ba06-4f04-854e-aefdd496714b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='33.3%']/parent::*</value>
      <webElementGuid>cdaa01a4-e96d-4309-b901-4d8c18a72042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[56]/div[2]/div/div</value>
      <webElementGuid>0a9c94bb-5022-47e5-8972-243a5ddfe773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '33.3%' or . = '33.3%')]</value>
      <webElementGuid>5cd52502-c2c8-4252-a5ab-6081d26bc7c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
