<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience3</name>
   <tag></tag>
   <elementGuidId>0f979a90-78d7-4307-8724-9d2f5345008f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[54]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#5c8ee11c6dc6405fafc15d6dd8d51823 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93fd065c-1566-4084-969d-fdb9e9295d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26.2%</value>
      <webElementGuid>1cee6969-3dd0-4b5e-8051-1d5f89da42be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5c8ee11c6dc6405fafc15d6dd8d51823&quot;)/div[1]</value>
      <webElementGuid>2807488e-67a1-44ee-b39c-a073c68c39fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5c8ee11c6dc6405fafc15d6dd8d51823']/div</value>
      <webElementGuid>0e18f464-226e-4a3e-bcc6-ae44a5d48e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[27]/following::div[9]</value>
      <webElementGuid>ef6cf8f9-64a1-4359-a7f4-f79c74863ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[28]/preceding::div[16]</value>
      <webElementGuid>cbb2385b-4d7e-46b0-863a-19bdff5b12de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='26.2%']/parent::*</value>
      <webElementGuid>352182b7-5f73-4eef-af2f-a44d544fa525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[54]/div[2]/div/div</value>
      <webElementGuid>f67faea0-7cec-4cb4-8a82-1228edf655e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '26.2%' or . = '26.2%')]</value>
      <webElementGuid>b55fb47d-c23e-48df-9aad-561b91492c26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
