<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentOfWomen</name>
   <tag></tag>
   <elementGuidId>0029bf86-522d-49ab-ae4a-8b9eabf00991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[16]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4611d8335f4e4eafbd515a4709c01f86 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>54c32c9e-7b6a-481b-924a-32d2dec43922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>d677b608-3374-451e-a6ef-549cc8f50b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4611d8335f4e4eafbd515a4709c01f86&quot;)/div[1]</value>
      <webElementGuid>e2f46a54-5e6e-4c8c-83ae-775b3cfe8467</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4611d8335f4e4eafbd515a4709c01f86']/div</value>
      <webElementGuid>83659c54-2302-4813-a8f8-f3bc55e8a7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Женщин, %'])[1]/following::div[3]</value>
      <webElementGuid>8a0ad409-96e3-4763-84f3-c32643980f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[8]/following::div[9]</value>
      <webElementGuid>4b737cbe-155d-4882-8590-84f18371c4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[9]/preceding::div[16]</value>
      <webElementGuid>77f9eb61-762c-4081-b557-9613973a8c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Динамика среднего возраста'])[1]/preceding::div[24]</value>
      <webElementGuid>2edfec2b-b27f-4d37-aae3-dc00b3dd1261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/div/div</value>
      <webElementGuid>659927f9-fd86-49a1-b79e-ca156807f6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '50%' or . = '50%')]</value>
      <webElementGuid>ee6b3abb-3791-4a2e-b044-bdd01365b2c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
