<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>precentSumPerson93</name>
   <tag></tag>
   <elementGuidId>1c6d5df7-3c6e-402d-ba23-8b27496da5f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='8d4c9697cdb24b3d866c7517cd5618ef']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8d4c9697cdb24b3d866c7517cd5618ef > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>506ea6c2-b60f-456d-9e79-1855f14ffc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>93 %</value>
      <webElementGuid>d530d50f-5fc9-4f96-afa3-884300f4d8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8d4c9697cdb24b3d866c7517cd5618ef&quot;)/div[1]</value>
      <webElementGuid>74480101-d903-4f25-9a36-072be5aafb6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8d4c9697cdb24b3d866c7517cd5618ef']/div</value>
      <webElementGuid>eb734fda-96a0-4624-b937-f76d1405afd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Общая укомплектованность персоналом'])[1]/following::div[3]</value>
      <webElementGuid>46bc967e-e828-4750-9317-30b97cc19900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[10]/following::div[9]</value>
      <webElementGuid>f2549dff-9bdd-45b6-8b13-205abc1135fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[11]/preceding::div[16]</value>
      <webElementGuid>9087235e-82e9-4f1c-9d4d-f3b429ac8bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Укомплектованность ПП'])[1]/preceding::div[24]</value>
      <webElementGuid>fc814395-3f72-4df6-a6e8-89cdad104b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='93 %']/parent::*</value>
      <webElementGuid>a5f5aaa0-eca9-4c39-ad99-1fa2ce5326ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div[2]/div/div</value>
      <webElementGuid>5dcafb29-9de5-4ac4-af00-6778574de22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '93 %' or . = '93 %')]</value>
      <webElementGuid>3b61b58f-1b6e-4f1b-9e27-569ff6ca970d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
