<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>totalNoList</name>
   <tag></tag>
   <elementGuidId>b77fdd1b-9b2d-4fb1-9eed-4380e2271073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bb0869408912475fbe00ff3f08e6215a']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bb0869408912475fbe00ff3f08e6215a > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0434b6a-5a3d-4f45-bb9a-95a865050f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 793</value>
      <webElementGuid>ef79c426-973f-4d67-a414-2ad87fee9b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bb0869408912475fbe00ff3f08e6215a&quot;)/div[1]</value>
      <webElementGuid>13bd99e4-a69f-4233-80bf-ac02f83ecceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bb0869408912475fbe00ff3f08e6215a']/div</value>
      <webElementGuid>9bccee15-60ae-4d2b-9623-789fd6ca50b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Средняя несписочная численность ГК Россети'])[1]/following::div[3]</value>
      <webElementGuid>c704cf89-ea53-4f1e-8aea-c2a3b0dc6003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[14]/following::div[9]</value>
      <webElementGuid>02d917e7-06e5-483e-85f1-167de985030f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[15]/preceding::div[16]</value>
      <webElementGuid>9cc32ec4-27e4-42b1-9f54-5462d7002c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Средняя общая численность ГК Россети'])[1]/preceding::div[24]</value>
      <webElementGuid>1ca3fdc9-cc0d-4628-aa1c-c981b3800b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1 793']/parent::*</value>
      <webElementGuid>101cfb53-8329-4472-bf47-d6c6773d5130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div[2]/div/div</value>
      <webElementGuid>99b69886-8b6a-489f-b6e3-b5fca077dfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1 793' or . = '1 793')]</value>
      <webElementGuid>caf00e73-40c7-4111-878a-81d7b202ff4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
