<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>фильтр Деятельность ДЗО</name>
   <tag></tag>
   <elementGuidId>bf20f791-95bb-4468-99b3-01218f481629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dbef937fa4ff462ea89afa9cb5284a21']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dbef937fa4ff462ea89afa9cb5284a21 > div.rb-filter-container.not-selectable.rb-filter-multi-selection > div.rb-filter-header-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>49903e50-4577-46f9-b986-c75486429ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rb-filter-header-container</value>
      <webElementGuid>e0d49eae-c602-48e4-9056-23e6bac78653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Все</value>
      <webElementGuid>0358e65f-253b-4d3b-9f92-c2e39e2dbfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dbef937fa4ff462ea89afa9cb5284a21&quot;)/div[@class=&quot;rb-filter-container not-selectable rb-filter-multi-selection&quot;]/div[@class=&quot;rb-filter-header-container&quot;]</value>
      <webElementGuid>96fffa41-699d-40c8-9421-6ce0a2a5d635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dbef937fa4ff462ea89afa9cb5284a21']/div/div</value>
      <webElementGuid>bbb99ee2-7fcc-4574-a4ee-699ce2218246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Вид деятельности ДЗО'])[1]/following::div[4]</value>
      <webElementGuid>f87580fd-3571-4109-9477-f159b27b3660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[20]/following::div[10]</value>
      <webElementGuid>1f9fe10d-a307-436f-9894-3736170d0d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выбранные значения'])[3]/preceding::div[2]</value>
      <webElementGuid>0a257b94-1fc0-4996-8a6a-7b7a819da415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[40]/div[2]/div/div/div</value>
      <webElementGuid>29193340-142c-40d5-a985-fb1ce2fe0034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Все' or . = 'Все')]</value>
      <webElementGuid>1983fdf3-30a4-4ff6-a3de-1b2e48bdfcec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
