<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience1</name>
   <tag></tag>
   <elementGuidId>f71a5b04-501c-471d-b0cb-204d1821c332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[52]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9e572aa41f764616a5a15f3af5146008 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a4b2d60-a7a8-4d46-865a-8a3fe27a7661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7.1%</value>
      <webElementGuid>6e8f72cb-cd26-43c0-9538-d65f25183cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9e572aa41f764616a5a15f3af5146008&quot;)/div[1]</value>
      <webElementGuid>5ce17819-e988-41e6-81bf-807d62d6c98a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9e572aa41f764616a5a15f3af5146008']/div</value>
      <webElementGuid>eb3119d5-5f93-4397-8d85-4573e44086c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[26]/following::div[9]</value>
      <webElementGuid>71504c8a-08d6-438a-baee-2bfd491d864c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[27]/preceding::div[16]</value>
      <webElementGuid>12f350b4-583f-4410-a1fd-3ccab479bc56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7.1%']/parent::*</value>
      <webElementGuid>80d4e078-7cd1-4d4a-badf-743fe4742701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[52]/div[2]/div/div</value>
      <webElementGuid>19eb32a7-49b7-4bd7-b112-7bfaefc6579a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '7.1%' or . = '7.1%')]</value>
      <webElementGuid>d6a1866d-61c5-4049-a63a-b7cb334b5473</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
