<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience20</name>
   <tag></tag>
   <elementGuidId>94fffc40-4eb9-44ad-b0ab-afbd7c68dc59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[58]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1fb46c04cda24f6794609515448b1180 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0dcd917f-8142-432d-b7a2-7f880e516fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>33.3%</value>
      <webElementGuid>67c10e93-af6f-4e95-921b-a79c97b2feaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1fb46c04cda24f6794609515448b1180&quot;)/div[1]</value>
      <webElementGuid>e3c90437-89b3-4998-8666-9f9cfb03e8d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1fb46c04cda24f6794609515448b1180']/div</value>
      <webElementGuid>1ddd10bf-a7a6-41ce-aa6a-404d4c09555b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[29]/following::div[9]</value>
      <webElementGuid>61301420-47c7-4e54-8566-b6353ab8c93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[30]/preceding::div[16]</value>
      <webElementGuid>4891f208-5796-47b9-91e2-fafeb77f90ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[58]/div[2]/div/div</value>
      <webElementGuid>ca9b6c65-e904-4cad-81e7-0a9f52beac66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '33.3%' or . = '33.3%')]</value>
      <webElementGuid>0b685a06-69d2-4530-99bc-1c0ed6a81811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
