<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience40</name>
   <tag></tag>
   <elementGuidId>652fb604-6bd9-485b-91a3-97572ef81bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[62]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#99636123779f43339788d9654abeeb42 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>63dcf26a-8929-433a-9d3f-c2fecbb4bca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.0%</value>
      <webElementGuid>e6c77279-d46c-41d9-b2bf-62b4c6076fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;99636123779f43339788d9654abeeb42&quot;)/div[1]</value>
      <webElementGuid>4cb0c014-5f2e-4ec3-831f-fec2195653f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='99636123779f43339788d9654abeeb42']/div</value>
      <webElementGuid>610065f3-fc08-46f4-a6c6-fc369e844ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[31]/following::div[9]</value>
      <webElementGuid>87e2a8c8-02f5-4181-bbcc-8e994a690693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[32]/preceding::div[16]</value>
      <webElementGuid>93546418-0220-4bc5-96d1-8461e9783354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[62]/div[2]/div/div</value>
      <webElementGuid>d61d65f0-343b-47b2-9207-c7644d406567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0.0%' or . = '0.0%')]</value>
      <webElementGuid>49ecaa97-7d7b-499a-8992-fa82cac29c65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
