<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience10</name>
   <tag></tag>
   <elementGuidId>f4d9b75a-de3c-4c29-9282-9bfcbdc53a48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[56]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eba1a8b66362466b815e0de28477c634 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>517e3ea3-962b-46e0-8403-e4879c5b43e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>33.3%</value>
      <webElementGuid>f4ce9088-0736-45f5-902d-8f08801fbd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eba1a8b66362466b815e0de28477c634&quot;)/div[1]</value>
      <webElementGuid>c9a02d3d-ebe4-421a-aef3-25520594eb58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eba1a8b66362466b815e0de28477c634']/div</value>
      <webElementGuid>70d96319-bb8d-4213-8966-faa4607ecd95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[28]/following::div[9]</value>
      <webElementGuid>dfedd0f6-fb55-4428-a6f7-40a2d5eaf0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[29]/preceding::div[16]</value>
      <webElementGuid>9e10b024-7dd1-4e6d-8cd7-4c52c73b98f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='33.3%']/parent::*</value>
      <webElementGuid>f262f769-0789-48a1-b1f6-90387826a0f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[56]/div[2]/div/div</value>
      <webElementGuid>5f2618dd-90bf-4c62-8eaa-e374abe76963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '33.3%' or . = '33.3%')]</value>
      <webElementGuid>348b1ec4-6cb8-4946-86af-7813ff2281c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
