<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentEducationHigher</name>
   <tag></tag>
   <elementGuidId>64387e15-ffdd-406f-985c-84dba9768625</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[50]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#468ab12773094e5091f46fad9889ea76 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55140a72-30ef-4f45-b311-9a80d6c123f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>96.4%</value>
      <webElementGuid>bb4f9136-3e4d-4da5-9444-5e6ab5b1afac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;468ab12773094e5091f46fad9889ea76&quot;)/div[1]</value>
      <webElementGuid>fe73addd-bbef-4c79-a319-590a3385560f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='468ab12773094e5091f46fad9889ea76']/div</value>
      <webElementGuid>000227bb-4e0b-4083-8202-fa2d9db4f7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Образование (в % и чел.) - копия 1'])[2]/following::div[3]</value>
      <webElementGuid>75941232-d3b4-4d9a-bae1-e4de9c27b7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[25]/following::div[9]</value>
      <webElementGuid>4299add0-f898-46dd-b4b6-e27b339a62c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[26]/preceding::div[16]</value>
      <webElementGuid>a1be065b-982e-4e30-bb5f-6526b698e70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='96.4%']/parent::*</value>
      <webElementGuid>179adda3-ccff-4ff1-9079-eb72da8e01f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[50]/div[2]/div/div</value>
      <webElementGuid>8fca23be-bb9e-499a-9775-0d84097cab05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '96.4%' or . = '96.4%')]</value>
      <webElementGuid>d3eaae6f-4678-4a67-8735-7653268f70f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
