<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentEducationLower</name>
   <tag></tag>
   <elementGuidId>d916b84d-90d9-41f9-aab8-e2792200eb9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[48]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#3bb40ffd75c74129af0cd6133210dec2 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0817f69-81f4-45ab-b22b-6efa3330a18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3.6%</value>
      <webElementGuid>412c9044-83b1-48e5-ac98-402e0f1ed2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3bb40ffd75c74129af0cd6133210dec2&quot;)/div[1]</value>
      <webElementGuid>dceaa349-3c4a-4e33-b7ae-8f12e1a7ebac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3bb40ffd75c74129af0cd6133210dec2']/div</value>
      <webElementGuid>b57887ce-0096-4d71-b168-d1383bcd964c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Образование (в % и чел.) - копия 1'])[1]/following::div[3]</value>
      <webElementGuid>bef42f7e-849e-4884-8751-d7cd1c94fa59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[24]/following::div[9]</value>
      <webElementGuid>8ffcaab8-c235-45d7-bfb4-febfd0fca6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[25]/preceding::div[16]</value>
      <webElementGuid>3dd7b24d-b6c0-4c5e-bbb1-17d9009ed387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Образование (в % и чел.) - копия 1'])[2]/preceding::div[24]</value>
      <webElementGuid>dcf2308f-e374-4463-a4ca-10d86db1bde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3.6%']/parent::*</value>
      <webElementGuid>7702f8bf-e101-4f70-8fb0-7518c97f5729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[48]/div[2]/div/div</value>
      <webElementGuid>aa4bea95-334a-4045-a44f-244d3d824274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '3.6%' or . = '3.6%')]</value>
      <webElementGuid>c38c1427-9a2f-4d53-b287-9e50f0069d90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
