<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentAgeBelow50</name>
   <tag></tag>
   <elementGuidId>2e040ac6-e806-427e-bdca-89eee5a8ef13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[70]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#87b557eb680846eb8f1852a2f171a646 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ccf6556-1c13-453f-83f5-4c464f7e7503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30.9%</value>
      <webElementGuid>f18cc340-d537-40fd-b119-fb9722f42441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;87b557eb680846eb8f1852a2f171a646&quot;)/div[1]</value>
      <webElementGuid>b8160875-0550-4987-a563-e3fce158dcff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='87b557eb680846eb8f1852a2f171a646']/div</value>
      <webElementGuid>1d22c986-2e0b-4dd8-a374-3fdb160dec3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Возраст (в % и чел.) - копия 1'])[2]/following::div[3]</value>
      <webElementGuid>cdba2864-2c8a-408e-b7ba-fb5406214159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[35]/following::div[9]</value>
      <webElementGuid>5da8318f-4697-433c-952c-3e71486222d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Экспорт данных'])[1]/preceding::div[17]</value>
      <webElementGuid>58f9ae05-ca9c-4653-828a-123c20dc9315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отменить загрузку'])[1]/preceding::div[18]</value>
      <webElementGuid>ce4d476a-73fd-475b-a82a-dc65dcd1a532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30.9%']/parent::*</value>
      <webElementGuid>3996a4c1-4844-4256-83de-0afe5e09261d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[70]/div[2]/div/div</value>
      <webElementGuid>bde3c7dc-0aed-44e1-a358-17090f493488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '30.9%' or . = '30.9%')]</value>
      <webElementGuid>5164af8b-e576-4424-beb9-95faca23c48b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
