<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentOfWomen</name>
   <tag></tag>
   <elementGuidId>b03ab0aa-e0ac-4e78-bfd0-a5a54de78dc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[16]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4611d8335f4e4eafbd515a4709c01f86 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>118f0863-a732-45ba-9816-8c250d8871a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>b068d797-a425-4c32-a698-13b56bffcbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4611d8335f4e4eafbd515a4709c01f86&quot;)/div[1]</value>
      <webElementGuid>2a2dc292-158e-4645-bd49-c7418691e375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4611d8335f4e4eafbd515a4709c01f86']/div</value>
      <webElementGuid>f550a868-bb2a-476c-a465-47745fd06e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Женщин, %'])[1]/following::div[3]</value>
      <webElementGuid>e4f63c29-5add-4456-935b-9e500882c5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[8]/following::div[9]</value>
      <webElementGuid>8c471f05-7c14-48bb-9fa7-848cb47d58a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[9]/preceding::div[16]</value>
      <webElementGuid>f2daa6d1-202d-4c22-94de-b66121e0bb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Динамика среднего возраста'])[1]/preceding::div[24]</value>
      <webElementGuid>fe26a198-6c0a-419a-9bbe-b49ea447aa53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/div/div</value>
      <webElementGuid>ce29864b-1f8f-4705-baf5-ce7372405228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '50%' or . = '50%')]</value>
      <webElementGuid>1df9a02a-855f-4911-839a-d67bb2b49765</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
