<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentAgeAbove35</name>
   <tag></tag>
   <elementGuidId>8fa8fb67-125c-41e2-9017-1dc9ab257478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[68]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#557861dc23be46dab313d05f1259ca9e > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9993089-9655-476a-9e22-11129fba5441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>43.9%</value>
      <webElementGuid>00b54795-d732-4dbe-b713-4e520a5a636b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;557861dc23be46dab313d05f1259ca9e&quot;)/div[1]</value>
      <webElementGuid>7cb29afe-7c1e-425c-abeb-f0606b6f855f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='557861dc23be46dab313d05f1259ca9e']/div</value>
      <webElementGuid>def9c963-5657-440c-9790-5d078b6f35b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Возраст (в % и чел.) - копия 1'])[1]/following::div[3]</value>
      <webElementGuid>ce2f90bf-f0c3-4b5e-8247-50bf6b668aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[34]/following::div[9]</value>
      <webElementGuid>dad64ac6-d16e-4f5c-abaa-54965dfc9c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[35]/preceding::div[16]</value>
      <webElementGuid>8dc3e111-1906-4c28-8a7d-b930bbc391c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Возраст (в % и чел.) - копия 1'])[2]/preceding::div[24]</value>
      <webElementGuid>4800ccaa-5247-47c3-903a-19adfbf3ff7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='43.9%']/parent::*</value>
      <webElementGuid>ba892c2f-8fd8-4a72-8f5e-b8bc4122fa91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[68]/div[2]/div/div</value>
      <webElementGuid>a8679aef-8094-4edf-bb92-62be153b7796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '43.9%' or . = '43.9%')]</value>
      <webElementGuid>fd66bafd-95a4-4b30-b801-5a4f513f374d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
