<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience3</name>
   <tag></tag>
   <elementGuidId>28c404aa-cba0-4e3a-b6fc-6f52a35ecc22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[54]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#5c8ee11c6dc6405fafc15d6dd8d51823 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6974f69d-90c8-4ef6-badd-7d4980bc5f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26.2%</value>
      <webElementGuid>8e6969a4-f26d-4bf1-b0fa-fa9672f91548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5c8ee11c6dc6405fafc15d6dd8d51823&quot;)/div[1]</value>
      <webElementGuid>39853b6a-784f-4de1-9a95-c352e1de942b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5c8ee11c6dc6405fafc15d6dd8d51823']/div</value>
      <webElementGuid>65da67f9-9a45-4905-b673-419458096586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[27]/following::div[9]</value>
      <webElementGuid>6b06942b-d3e6-4fb1-be2d-47c80f5dc1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[28]/preceding::div[16]</value>
      <webElementGuid>30302fd8-66b3-46f4-b5d9-98ef0ae9581a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='26.2%']/parent::*</value>
      <webElementGuid>59848a23-e303-4c25-8f87-ec41376a14b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[54]/div[2]/div/div</value>
      <webElementGuid>00e0e04e-530b-4362-b5b9-1268bcf8f7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '26.2%' or . = '26.2%')]</value>
      <webElementGuid>218bb785-e6a5-4706-a0c7-c67b177d6d58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
