<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperienceMoreThan40</name>
   <tag></tag>
   <elementGuidId>1abb4a32-c08d-40a0-a245-8816e820b80a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[64]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e3d635b1af904eebaca64a28d311db1c > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e96c204f-2a1d-4744-9222-704fdc959e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.0%</value>
      <webElementGuid>baff429d-3c1e-4929-ae8d-3b2a805cbd15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e3d635b1af904eebaca64a28d311db1c&quot;)/div[1]</value>
      <webElementGuid>2a0c0af0-7238-4e69-9f2b-d88722bfb478</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e3d635b1af904eebaca64a28d311db1c']/div</value>
      <webElementGuid>4d1551ed-9cbe-476c-948a-316f57726873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[32]/following::div[9]</value>
      <webElementGuid>a660d56c-9f60-4488-ace2-50687b959d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[33]/preceding::div[16]</value>
      <webElementGuid>a850c668-b261-4e05-a0da-dd62656c8949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Возраст (в % и чел.) - копия'])[1]/preceding::div[24]</value>
      <webElementGuid>1d889405-ce9b-46a6-8f06-609e7de66dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[64]/div[2]/div/div</value>
      <webElementGuid>72bb89ac-4e1c-433e-bbcb-5d5858e8b83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0.0%' or . = '0.0%')]</value>
      <webElementGuid>7881ffb7-3620-405d-9144-0a3cb4c565e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
