<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DZO</name>
   <tag></tag>
   <elementGuidId>842ab373-dae8-4c15-8401-3437a99104c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#widget-header-e7b741b5bd964408a0aa5ad1f85a1fe3 > a.va-widget-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='widget-header-e7b741b5bd964408a0aa5ad1f85a1fe3']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c609d65-af78-4ffb-aaca-fb8df827f570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>va-widget-header</value>
      <webElementGuid>4241a4e4-9c39-4377-983b-a43368827060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: title.text(), attr: title.linkEnabled() &amp;&amp; title.link().trim() ? { href: title.link().indexOf('http') == 0 ? title.link().trim() : '//' + title.link().trim() } : { href: false }, style: { 'text-align': title.textStyle.alignString(), color: title.textStyle.color(), 'font-size': title.textStyle.fontSize() + 'px', 'font-family': title.textStyle.fontFamily(), 'font-weight': title.textStyle.isBold() ? 'bold' : 'normal', 'font-style': title.textStyle.isItalic() ? 'italic' : 'normal', 'line-height': title.textStyle.lineHeight(), cursor: title.linkEnabled() ? 'pointer' : 'default' }</value>
      <webElementGuid>c4b924e0-5808-4a23-8f80-ec8568d1ade3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ДЗО</value>
      <webElementGuid>75804acf-df48-4d19-b3bb-7a79d0a23273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget-header-e7b741b5bd964408a0aa5ad1f85a1fe3&quot;)/a[@class=&quot;va-widget-header&quot;]</value>
      <webElementGuid>689c68c7-8629-4b2a-8bd0-4eacc377c751</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-header-e7b741b5bd964408a0aa5ad1f85a1fe3']/a</value>
      <webElementGuid>8973c701-dfe1-4550-b1eb-ab7c3b068317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ДЗО')]</value>
      <webElementGuid>30c04770-d64e-4708-8034-be8e5675016c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[5]/following::a[1]</value>
      <webElementGuid>ac76f9a9-1b78-49a8-a7c9-0c952a2802a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='_________________________________________'])[1]/following::a[1]</value>
      <webElementGuid>59d1782b-904d-4697-8f92-b184549923cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Все'])[1]/preceding::a[1]</value>
      <webElementGuid>0bd41a6b-3df2-445f-8bd1-0207a31381ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выбранные значения'])[1]/preceding::a[1]</value>
      <webElementGuid>411ad235-587e-4676-bc7f-519fa8bf60a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ДЗО']/parent::*</value>
      <webElementGuid>1607bd32-9735-4040-acdb-1a0483e8f1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/a</value>
      <webElementGuid>06f6b87d-f8b6-4a2b-81b6-8c85c33249e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'ДЗО' or . = 'ДЗО')]</value>
      <webElementGuid>2f789f52-5d5d-4116-9423-15a5a97e2a91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
