<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience10</name>
   <tag></tag>
   <elementGuidId>19ca1662-fe70-47a8-a78c-45457338f7b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[56]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eba1a8b66362466b815e0de28477c634 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7f4eec3-8cd6-428f-b442-c1c7e2816eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>33.3%</value>
      <webElementGuid>38a5b22a-0009-40fc-b3dd-8913f29a6e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eba1a8b66362466b815e0de28477c634&quot;)/div[1]</value>
      <webElementGuid>f65e8ba3-8384-4f67-ae1f-256c8de8392e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eba1a8b66362466b815e0de28477c634']/div</value>
      <webElementGuid>ca63d17f-e3fa-41aa-9542-f34a1efb72b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[28]/following::div[9]</value>
      <webElementGuid>a589a697-7d64-4f3c-b9ed-522fcf67e782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[29]/preceding::div[16]</value>
      <webElementGuid>c9f75ea4-adc0-416b-9115-39b298f50fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='33.3%']/parent::*</value>
      <webElementGuid>ff504d29-00c7-4e3b-b1b5-3d045ded9445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[56]/div[2]/div/div</value>
      <webElementGuid>fb7a1881-2d32-4bb5-b541-ed5294056608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '33.3%' or . = '33.3%')]</value>
      <webElementGuid>78a58896-d0ca-4019-8583-c14290e967bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
