<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience30</name>
   <tag></tag>
   <elementGuidId>ec172f55-7be9-4f0d-88a0-84faeee78297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[58]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1fb46c04cda24f6794609515448b1180 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>290a92f7-3beb-4964-93a4-b155cd659517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>33.3%</value>
      <webElementGuid>8b62c451-7e65-4075-823b-120f94dd2446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1fb46c04cda24f6794609515448b1180&quot;)/div[1]</value>
      <webElementGuid>71442363-87bf-4c65-abfa-b0f72d0d3be3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1fb46c04cda24f6794609515448b1180']/div</value>
      <webElementGuid>9e644fb6-45db-40bc-9978-e21e16b4ec70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[29]/following::div[9]</value>
      <webElementGuid>98ad8728-7dde-45e9-a8d2-7e399be76657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[30]/preceding::div[16]</value>
      <webElementGuid>386c804c-0034-4833-8f0a-a072ffbed73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[58]/div[2]/div/div</value>
      <webElementGuid>e5f0995c-36c7-43a1-aae3-479995dcc9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '33.3%' or . = '33.3%')]</value>
      <webElementGuid>52c9371b-d870-4536-8579-911c0b8a2d49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
