<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentEducationMiddle</name>
   <tag></tag>
   <elementGuidId>82b1b6db-8be8-4fc7-ae1e-510043819eb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[46]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8fb84bf3d2cb4a42a88f485f2f821e81 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5e3dec36-51d7-46f1-a4e9-de0bff284c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.0%</value>
      <webElementGuid>34b73663-65fd-4088-8940-54918faa26b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8fb84bf3d2cb4a42a88f485f2f821e81&quot;)/div[1]</value>
      <webElementGuid>91927122-5055-404f-a30c-38a2f9099752</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8fb84bf3d2cb4a42a88f485f2f821e81']/div</value>
      <webElementGuid>2dc15c62-09ea-44df-a0b9-8af6f46132a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Образование (в % и чел.) - копия'])[1]/following::div[3]</value>
      <webElementGuid>4bd5aabf-0ce2-4763-b8ec-827fe7b72c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[23]/following::div[9]</value>
      <webElementGuid>11826cb9-2880-4939-aa45-17df6b15f007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[24]/preceding::div[16]</value>
      <webElementGuid>8216718f-c671-405e-96d0-44db1c6abe1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Образование (в % и чел.) - копия 1'])[1]/preceding::div[24]</value>
      <webElementGuid>ff024400-ab74-4300-9a67-758d5a6a6bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0.0%']/parent::*</value>
      <webElementGuid>af242b20-7a6b-4929-89eb-004d29edd88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[46]/div[2]/div/div</value>
      <webElementGuid>76d9f5d2-4f8a-47de-99d8-175cc79455a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0.0%' or . = '0.0%')]</value>
      <webElementGuid>cae93283-42cf-4ae2-8bc5-ece20660560b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
