<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience1</name>
   <tag></tag>
   <elementGuidId>92c8b4ca-d48a-4d1a-b8ed-e98be064d59c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[52]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9e572aa41f764616a5a15f3af5146008 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d08e8c8f-deac-42d0-87ab-84c4442f8893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7.1%</value>
      <webElementGuid>205f4513-c137-41a9-a214-a00f01da63d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9e572aa41f764616a5a15f3af5146008&quot;)/div[1]</value>
      <webElementGuid>84419bd1-9cf0-42e8-9b17-cfdcb920e049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='9e572aa41f764616a5a15f3af5146008']/div</value>
      <webElementGuid>41fe7921-0c2b-4ad9-a098-758c5c6eb15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[26]/following::div[9]</value>
      <webElementGuid>b70082da-b352-442a-9056-72330506445c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[27]/preceding::div[16]</value>
      <webElementGuid>b265d99b-970f-4071-901d-30113df33cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7.1%']/parent::*</value>
      <webElementGuid>17a66aa0-cccd-4d6c-b9f1-97e06cffdd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[52]/div[2]/div/div</value>
      <webElementGuid>a601b8f2-f12e-4cc5-978f-738d37f63a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '7.1%' or . = '7.1%')]</value>
      <webElementGuid>1f33f2c1-7788-41d6-805c-8d21b631db83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
