<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience40</name>
   <tag></tag>
   <elementGuidId>496ef582-d0ee-48e0-b4b7-df74dfdef2a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[62]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#99636123779f43339788d9654abeeb42 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2e9ff9c-a7e9-4b08-95e5-32e0e585f3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.0%</value>
      <webElementGuid>fc70120f-341a-4b1e-89ff-daa2636496f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;99636123779f43339788d9654abeeb42&quot;)/div[1]</value>
      <webElementGuid>dd529dc2-2a6d-4008-8c00-2c5ae538704e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='99636123779f43339788d9654abeeb42']/div</value>
      <webElementGuid>416ebd4e-829c-447f-a048-00f9184c777b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[31]/following::div[9]</value>
      <webElementGuid>47c8cbda-f8a8-482d-ae6d-6408d793bbdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[32]/preceding::div[16]</value>
      <webElementGuid>4b220f95-5ab0-43f1-aaf6-fafdd56f3505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[62]/div[2]/div/div</value>
      <webElementGuid>ac3d196f-d821-4855-97c0-9aaeb1d27e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '0.0%' or . = '0.0%')]</value>
      <webElementGuid>db445006-30cc-49cd-94b2-86bde63d098d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
