<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentEducationHigher</name>
   <tag></tag>
   <elementGuidId>6196994c-2217-4c39-a4ed-099d2257958a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[50]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#468ab12773094e5091f46fad9889ea76 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e24fd6af-be34-4603-ae5d-31dc3bdbacf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>96.4%</value>
      <webElementGuid>a52795a3-ade2-41bf-a401-1fc651aff621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;468ab12773094e5091f46fad9889ea76&quot;)/div[1]</value>
      <webElementGuid>623b67fa-c367-407a-8bfc-b0fa0f32c6e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='468ab12773094e5091f46fad9889ea76']/div</value>
      <webElementGuid>931ff94c-16c8-4bd8-aca0-acf8fce87699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Образование (в % и чел.) - копия 1'])[2]/following::div[3]</value>
      <webElementGuid>ae156954-dfa8-4d81-9c13-5f6f1fe5d90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[25]/following::div[9]</value>
      <webElementGuid>3b28bec5-0e16-49ea-bc3c-1f3cc402b2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[26]/preceding::div[16]</value>
      <webElementGuid>01d086f5-b9d1-4c02-a3d9-e670e06627ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='96.4%']/parent::*</value>
      <webElementGuid>50ca8e6c-2236-45db-b6d0-2207eb99f1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[50]/div[2]/div/div</value>
      <webElementGuid>035d49e7-f993-4510-9905-7da3f302c54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '96.4%' or . = '96.4%')]</value>
      <webElementGuid>617adbec-7d34-40de-8e73-07520da91b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
