<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentExperience3</name>
   <tag></tag>
   <elementGuidId>4da88b74-509e-41ee-927a-d0cb58109b17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[54]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#5c8ee11c6dc6405fafc15d6dd8d51823 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>55c6f5c9-cdd4-4b76-9463-a0745abf8b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26.2%</value>
      <webElementGuid>65d00250-f19a-4ec7-bb41-ed35bc12454e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5c8ee11c6dc6405fafc15d6dd8d51823&quot;)/div[1]</value>
      <webElementGuid>5855621b-691a-4ab0-9a69-63fd4fa76a98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5c8ee11c6dc6405fafc15d6dd8d51823']/div</value>
      <webElementGuid>3e7a580d-c008-4490-b6de-9b3679bb0a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[27]/following::div[9]</value>
      <webElementGuid>debfa8de-3fed-4d6d-a583-7b97c7dc7572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[28]/preceding::div[16]</value>
      <webElementGuid>023779d1-e40a-4e72-8201-74f1c26dfa23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='26.2%']/parent::*</value>
      <webElementGuid>97c6a01b-c340-4c4a-98bc-03d60e610e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[54]/div[2]/div/div</value>
      <webElementGuid>a1a43acd-3e8a-4628-8dd0-4e41da4c34a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '26.2%' or . = '26.2%')]</value>
      <webElementGuid>83dce13c-ad0e-4eda-af12-9e8dc80c99a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
