<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentAgeAbove35</name>
   <tag></tag>
   <elementGuidId>869dbe82-fa35-492b-8689-68d4da14d7ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[68]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#557861dc23be46dab313d05f1259ca9e > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ec37b22-b538-433e-87b5-df97fc49e332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>43.9%</value>
      <webElementGuid>2f7e2fa9-6d10-4327-a267-6198e07876f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;557861dc23be46dab313d05f1259ca9e&quot;)/div[1]</value>
      <webElementGuid>b797d4f7-fec8-4f81-b32b-8b1441453407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='557861dc23be46dab313d05f1259ca9e']/div</value>
      <webElementGuid>b3f432de-0477-4505-9b80-8adda714fce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Возраст (в % и чел.) - копия 1'])[1]/following::div[3]</value>
      <webElementGuid>dcd7bbda-3a20-4fa0-9f7a-b3570d558cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[34]/following::div[9]</value>
      <webElementGuid>f7c623ed-016e-48c1-a18a-d71e6bb84114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[35]/preceding::div[16]</value>
      <webElementGuid>7337f9a1-dbcc-4a6d-9e75-7d1e502fd466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Возраст (в % и чел.) - копия 1'])[2]/preceding::div[24]</value>
      <webElementGuid>8d2b6e94-e92b-49f6-83a6-75ab359e468b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='43.9%']/parent::*</value>
      <webElementGuid>f581c5c5-e6ed-4fb1-b868-d4c00c18f145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[68]/div[2]/div/div</value>
      <webElementGuid>d9d2c487-7f8d-43bb-89cb-6d4372fd691c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '43.9%' or . = '43.9%')]</value>
      <webElementGuid>c33d8d7a-e26d-42cd-952b-da1c5c7f54a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
