<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>percentAgeBelow35</name>
   <tag></tag>
   <elementGuidId>663faeb0-19ce-47a1-80aa-b1f9b0bc5442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[66]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cfc02c8d002a4705a7ba9cbba6933bbd > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bbf052f0-622d-4a82-80e7-b4544cf1cfe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25.2%</value>
      <webElementGuid>f6b017bd-eba5-4e33-95fc-0c109f982aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfc02c8d002a4705a7ba9cbba6933bbd&quot;)/div[1]</value>
      <webElementGuid>4add7fe4-67ae-4461-b4cf-cfda13a58f47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cfc02c8d002a4705a7ba9cbba6933bbd']/div</value>
      <webElementGuid>cd6f9dbd-391a-4b18-9be7-21fdf909be46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Возраст (в % и чел.) - копия'])[1]/following::div[3]</value>
      <webElementGuid>0e72cda2-98a2-4884-b532-09f9127c5bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[33]/following::div[9]</value>
      <webElementGuid>93363dbe-2d8f-46e8-8954-819bc9bd0c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[34]/preceding::div[16]</value>
      <webElementGuid>82ada239-9075-4602-a3ab-342390bd8768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Возраст (в % и чел.) - копия 1'])[1]/preceding::div[24]</value>
      <webElementGuid>f0d1e3de-38da-4641-960e-c44ae9b056d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='25.2%']/parent::*</value>
      <webElementGuid>79742230-6d45-44fb-9614-7d2ed5938880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[66]/div[2]/div/div</value>
      <webElementGuid>54b36460-239e-4e34-ac99-f6d047f3566f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '25.2%' or . = '25.2%')]</value>
      <webElementGuid>87a37cee-2c1d-4836-8653-ea81bab507e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
